services:
  watchtower:
    image: nickfedor/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=10 # Poll every 10 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    command: my-node-pipeline-app
  my-node-pipeline-app:
    image: levonml/my-node-pipeline-app:latest
    ports:
      - 3000:8080
    container_name: my-node-pipeline-app
